#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt update
sudo apt-get install -y haproxy
echo "listen 4369-lb-01 " | sudo tee -a /etc/haproxy/haproxy.cfg
echo "bind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4369-web-01 3.94.163.186:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4438-web-02 34.224.21.107:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
