#!/usr/bin/env bash
# Configure your Nginx server so that listens port 80

sudo apt-get update
sudo apt-get -y install nginx
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
