#!/usr/bin/env bash
# Configure your Nginx server so that listens port 80

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=_Yhyp-_hX2s&ab_channel=msvogue23 permanent;' /etc/nginx/sites-available/default
service nginx start
