#!/usr/bin/env bash
# Configure your Nginx server so that listens port 80

sudo apt-get update
sudo apt-get -y install nginx
sed -i '/listen 80' /etc/nginx/sites-available/default
service nginx start
