#!/usr/bin/env bash
# script that gives you information about the school file.

FILE="school"
if [ -e "$FILE" ]
then
	echo "school file exists"

for i in $FILE
do
	if [ -s "$FILE" ]
	then
        # The file is not-empty.
        echo "school file is not empty"
	else
        # The file is empty.
        echo "school file is empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "school is a regular file"
	fi
done
else
        echo "school file does not exist"
fi
